<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EasyTestAufgabe.Domain\EasyTestAufgabe.Domain.csproj" />
    <ProjectReference Include="..\EasyTestAufgabe.Infrastructure\EasyTestAufgabe.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
